### ISSUE TITLE
cuda 10.1 containers broken

### ISSUE THREAD

**Issue by havogt** [GridTools/gridtools-docker#14]
It seems I broke the cuda 10.1 images, I don't know how...
Either we recover them or we should remove them from dockerhub.

**Comment by havogt** [comment]
Additionally clang 9 with cuda 11.0 is broken.

**Comment by havogt** [comment]
I believe the current state is:
- clang+cuda 11 images contains actually cuda 10.1
- clang+cuda 10.1 is ok
- cuda 10.1 (with gcc) is broken
- cuda 11.0 is ok

**Comment by havogt** [comment]
After my lastes fix cuda 10.1 images should be good again

**Comment by fthaler** [comment]
All images have been moved to CUDA 11
